Traceback (most recent call last):
  File "learning_test.py", line 364, in <module>
    main()
  File "learning_test.py", line 355, in main
    loop.run_until_complete(run())
  File "/home/dmitry/projects/ci-sim/tol-revolve/.venv/local/lib/python2.7/site-packages/trollius/base_events.py", line 350, in run_until_complete
    return future.result()
  File "/home/dmitry/projects/ci-sim/tol-revolve/.venv/local/lib/python2.7/site-packages/trollius/futures.py", line 284, in result
    compat.reraise(type(self._exception), self._exception, exc_tb)
  File "/home/dmitry/projects/ci-sim/tol-revolve/.venv/local/lib/python2.7/site-packages/trollius/tasks.py", line 252, in _step
    result = coro.send(value)
  File "/home/dmitry/projects/ci-sim/tol-revolve/scripts/learning-test/../../tol/triangle_of_life/learning.py", line 105, in insert_brain
    pb_brain = self.nn_parser.genotype_to_brain(brain_genotype)
  File "/home/dmitry/projects/ci-sim/tol-revolve/scripts/learning-test/../../tol/triangle_of_life/convert/convert.py", line 42, in genotype_to_brain
    self._parse_connection_genes(genotype, brain, neuron_map)
  File "/home/dmitry/projects/ci-sim/tol-revolve/scripts/learning-test/../../tol/triangle_of_life/convert/convert.py", line 74, in _parse_connection_genes
    from_id = neuron_map[conn_gene.neuron_from]
KeyError: <tol.triangle_of_life.encoding.genes.Neuron instance at 0x7f34dcc09c68>

